basePath: /rest/api/v1
consumes:
- application/json
definitions:
  Calendar service authorization response - error:
    properties:
      error:
        type: string
    type: object
  Calendar service authorization response - success:
    properties:
      authorization_url:
        type: string
    type: object
  Calendar service callback response - error:
    properties:
      error:
        type: string
    type: object
  Calendar service callback response - success:
    properties:
      message:
        type: string
    type: object
  Calendar service clear response - error:
    properties:
      error:
        type: string
    type: object
  Calendar service clear response - success:
    properties:
      message:
        type: string
    type: object
  Calendar service revoke response - error:
    properties:
      error:
        type: string
    type: object
  Calendar service revoke response - success:
    properties:
      message:
        type: string
    type: object
  Configuration get response - error:
    properties:
      error:
        type: string
    type: object
  Configuration get response - success:
    properties:
      dualis:
        default: {}
        type: object
      general:
        default: {}
        type: object
      news:
        default: {}
        type: object
      stocks:
        default: {}
        type: object
      weather:
        default: {}
        type: object
    type: object
  Configuration post response - error:
    properties:
      error:
        type: string
    type: object
  Configuration post response - success:
    properties:
      message:
        type: string
    type: object
  Query response:
    properties:
      dialogflow:
        default: {}
        type: object
      response:
        default: {}
        type: object
    type: object
  Spotify service authorization response - error:
    properties:
      error:
        type: string
    type: object
  Spotify service authorization response - success:
    properties:
      authorization_url:
        type: string
    type: object
info:
  description: Middleware to connect frontend with backend.
  title: REST-API for Middleware
  version: 1.0.0
paths:
  /authorization/calendar-service:
    get:
      description: Authorize with google.
      operationId: get_calendar_service
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Calendar%20service%20authorization%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Calendar%20service%20authorization%20response%20-%20error'
      tags:
      - authorization
  /authorization/calendar-service/clear:
    get:
      description: Clear all authentication data, if you want to completely remove
        the permissions, call /authorization/calendar-service/revoke first.
      operationId: get_calendar_service_clear
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Calendar%20service%20clear%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Calendar%20service%20clear%20response%20-%20error'
      tags:
      - authorization
  /authorization/calendar-service/oauth2callback:
    get:
      description: Callback to be called after authentication.
      operationId: get_calendar_service_callback
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Calendar%20service%20callback%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Calendar%20service%20callback%20response%20-%20error'
      tags:
      - authorization
  /authorization/calendar-service/revoke:
    get:
      description: Revoke the permissions.
      operationId: get_calendar_service_revoke
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Calendar%20service%20revoke%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Calendar%20service%20revoke%20response%20-%20error'
      tags:
      - authorization
  /authorization/spotify-service:
    get:
      description: Authorize with Spotify.
      operationId: get_spotify_service
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Spotify%20service%20authorization%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Spotify%20service%20authorization%20response%20-%20error'
      tags:
      - authorization
  /authorization/spotify-service/oauth2callback:
    get:
      description: Callback to be called after authentication with Spotify.
      operationId: get_spotify_service_callback
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Calendar%20service%20callback%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Calendar%20service%20callback%20response%20-%20error'
      tags:
      - authorization
  /configuration/:
    get:
      description: Get configuration json.
      operationId: get_configuration_service
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Configuration%20get%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Configuration%20get%20response%20-%20error'
      tags:
      - configuration
    post:
      description: Post configuration json.
      operationId: post_configuration_service
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Configuration%20post%20response%20-%20success'
        '400':
          description: Error
          schema:
            $ref: '#/definitions/Configuration%20post%20response%20-%20error'
      tags:
      - configuration
  /configuration/stock-service/symbol:
    get:
      description: Get stock symbol by keyword.
      operationId: get_stock_service
      responses:
        '200':
          description: Success
      tags:
      - configuration
  /dialogflow/query:
    post:
      description: Query a message and return the dialogflow and service response.
      operationId: post_dialogflow
      parameters:
      - description: Message used to detect intent with dialogflow.
        in: query
        name: message
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Query%20response'
        '400':
          description: 'Missing argument: message'
      tags:
      - dialogflow
  /swagger/swagger.yml:
    get:
      description: Generate a swagger.yml file.
      operationId: get_swagger
      responses:
        '200':
          description: OK
      tags:
      - swagger
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags:
- description: Swagger APIs
  name: swagger
- description: Dialogflow APIs
  name: dialogflow
- description: Authorization APIs
  name: authorization
- description: Configuration APIs
  name: configuration
