version: "3.9"

services:
  dualis-service:
    container_name: dualis-container
    build: ./src/backend/services/dualis-service
    image: dualis-service:1.0
    ports:
      - "5550:5550"
    restart: always

  t2s-s2t-service:
    container_name: t2s-s2t-container
    build: ./src/backend/services/t2s-s2t-service
    image: t2s-s2t-service:1.0
    ports:
      - "5555:5555"
    restart: always

  calendar-service:
    container_name: calendar-container
    build: ./src/backend/services/calendar-service
    image: calendar-service:1.0
    ports:
      - "5560:5560"
    restart: always

  spotify-service:
    container_name: spotify-container
    build: ./src/backend/services/spotify-service
    image: spotify-service:1.0
    ports:
      - "5565:5565"
    restart: always

  weather-service:
    container_name: weather-container
    build: ./src/backend/services/weather-service
    image: weather-service:1.0
    ports:
      - "5570:5570"
    restart: always

  news-service:
    container_name: news-container
    build: ./src/backend/services/news-service
    image: news-service:1.0
    ports:
      - "5575:5575"
    restart: always
    
  maps-service:
    container_name: maps-container
    build: ./src/backend/services/maps-service
    image: maps-service:1.0
    ports:
      - "5580:5580"
    restart: always

  stock-service:
    container_name: stock-container
    build: ./src/backend/services/stock-service
    image: stock-service:1.0
    ports:
      - "5585:5585"
    restart: always

  node-webserver:
    container_name: frontend-container
    build: ./src/frontend
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes: 
      - mongo:/data/mongodb
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: aswe-pda

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: aswe-pda
      ME_CONFIG_MONGODB_AUTH_USERNAME: dev
      ME_CONFIG_MONGODB_AUTH_PASSWORD: dev
    depends_on:
      - mongo

  middleware:
    container_name: middleware-container
    build: ./src/backend/middleware
    image: middleware:1.0
    ports:
      - "5600:5600"
    restart: always

volumes:
  webserver:
  mongo:
