# Docker Engine release 18.06.0+
version: "3.7"

services:
  education-service:
    container_name: education-service
    build:
      context: ./education-service
      ports:
        - 5555:5555
      restart: always

  t2s-s2t-service-service:
    container_name: t2s-s2t-service-service
    build:
      context: ./t2s-s2t-service-service
      ports:
        - 5560:5560
      restart: always

  calendar-service:
    container_name: calendar-service
    build:
      context: ./calendar-service
      ports:
        - 5565:5565
      restart: always
  # TODO: Add more services
