version: "3.9"

services:
  education-service:
    container_name: education-container
    build: ./src/backend/services/education-service
    image: education-service:1.0
    ports:
      - "5550:5550"
    restart: always

  t2s-s2t-service:
    container_name: t2s-s2t-container
    build: ./src/backend/services/t2s-s2t-service
    image: t2s-s2t-service:1.0
    ports:
      - "5555:5555"
    env_file:
      - ./src/backend/services/t2s-s2t-service/ibm-credentials-t2s.env
      - ./src/backend/services/t2s-s2t-service/ibm-credentials-s2t.env
    restart: always

  calendar-service:
    container_name: calendar-container
    build: ./src/backend/services/calendar-service
    image: calendar-service:1.0
    ports:
      - "5560:5560"
    restart: always

  spotify-service:
    container_name: spotify-container
    build: ./src/backend/services/spotify-service
    image: spotify-service:1.0
    ports:
      - "5565:5565"
    restart: always

  apache-webserver:
    container_name: frontend-container
    build: ./src/frontend
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: "./src/frontend/src"
        target: "/var/www/html"
      - webserver:/data

volumes:
  webserver:
