<!-- Needed on every page -->
<title><?= isset($pageTitle) ? $pageTitle : "PDA"?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<!-- Load any needed frameworks here -->
<script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>
<!-- custom styles for site structure -->
<link href="/views/shared/shared.css" rel="stylesheet" />
<!-- Tailwind css -->
<!-- <link href="/views/shared/tailwind.css" rel="stylesheet" /> -->
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />