<!-- Needed on every page -->
<title><?= isset($pageTitle) ? $pageTitle : "Event Booking"?></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<!-- Load any needed frameworks here -->

<!-- custom styles for site structure -->
<link href="/views/shared/shared.css" rel="stylesheet">
<link href="/views/shared/header/header.css" rel="stylesheet">
<link href="/views/shared/footer/footer.css" rel="stylesheet">