<!-- Needed on every page -->
<title>J.A.R.V.I.S - PDA</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<!-- Load any needed frameworks here TODO: jquery failure-->
<!--<script type="text/javascript" src="/resources/assets/jquery/jquery.min.js"></script>-->
<!-- custom styles for site structure -->
<link href="/views/shared/shared.css" rel="stylesheet" />
<!-- Tailwind css -->
<!-- <link href="/views/shared/shared.css" rel="stylesheet" /> -->
<!--<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" />-->
<link href="/resources/css/tailwind.css" rel="stylesheet" />

<!-- favicon -->
<link rel="apple-touch-icon" sizes="57x57" href="/resources/icons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/resources/icons//apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/resources/icons//apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/resources/icons//apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/resources/icons//apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/resources/icons//apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/resources/icons//apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/resources/icons//apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/resources/icons//apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/resources/icons//android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/resources/icons//favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/resources/icons//favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/resources/icons//favicon-16x16.png">
<!--<link rel="manifest" href="/ressources/icons//manifest.json">-->
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">