<!DOCTYPE html>
<html lang="en" id="darkSwitch" class="dark">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link href="/views/setup/setup.css" rel="stylesheet">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="636994391836-i2q6bfh7qtkmhid850msbtvel5nv3kbr.apps.googleusercontent.com">
</head>
<body class="w-screen h-screen bg-gradient-to-b from-gray-300 to-gray-100 dark:from-gray-800 dark:to-gray-500">
<img class="absolute h-screen w-auto overflow-hidden transform -translate-x-1/2 opacity-60" src="/resources/images/jaarvishead.png" alt="">
<div class="snap-wrapper">
    <section class="snap-box box-1 flex flex-col justify-center items-center" data-index="1">
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/setup.html" ?>
        <div class="mt-20">
            <svg class="animate-bounce w-16 h-16 text-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7m0 0l-7-7m7 7V3" />
            </svg>
        </div>
    </section>
    <section class="snap-box box-2" data-index="2">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5">
                <h1 class="text-5xl text-gray-300 mb-8">
                    By what name should I adress you?
                </h1>
                <input type="text" class="w-full h-12 bg-transparent border-b text-gray-300 text-center shadow-2xl outline-none text-5xl text-turquoise-400">
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-3" data-index="3">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Please log in to your Google account
                </h1>
                <div class="g-signin2" data-onsuccess="onSignIn"></div>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-4" data-index="4">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Please log in to your Spotify account
                </h1>
                <div>
                    <button class="bg-gray-100 w-56 h-14 text-gray-300 flex flex-row justify-center items-center rounded-2xl text-gray-900 outline-none">
                        <img src="/resources/images/spotify.png" alt="" class="w-10 h-10 mr-4">
                        Log in with Spotify
                    </button>
                </div>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-5" data-index="5">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Choose your location and temperature unit
                </h1>
                <div class="flex flex-col justify-center items-center">
                    <button id="location" class="bg-gray-100 mb-6 w-56 h-14 text-gray-300 flex flex-row justify-center items-center rounded-2xl text-gray-900 outline-none">
                        Use my current location
                    </button>
                    <p id = "status"></p>
                    <a id="map-link" target="_blank"></a>
                    <div class="block">
                        <div class="mt-2">
                            <div>
                                <label class="inline-flex items-center">
                                    <input type="radio" class="form-radio text-turquoise-400" name="radio" value="1" checked>
                                    <span class="ml-2 text-gray-300">Celsius - °C</span>
                                </label>
                            </div>
                            <div>
                                <label class="inline-flex items-center">
                                    <input type="radio" class="form-radio text-turquoise-400" name="radio" value="2">
                                    <span class="ml-2 text-gray-300">Fahrenheit - °F</span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-6" data-index="6">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Choose your paper and news categories
                </h1>
                <label class="block w-full">
                    <?php include "{$_SERVER['DOCUMENT_ROOT']}/resources/templates/news.html" ?>
                </label>
                <div class="block mt-20">
                    <span class="text-gray-300">News categories</span>
                    <div class="mt-2 grid grid-cols-3 gap-4">
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400" checked>
                                <span class="ml-2 text-gray-300">Business</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">Entertainment</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">General</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">Health</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">Science</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">Sports</span>
                            </label>
                        </div>
                        <div>
                            <label class="inline-flex items-center">
                                <input type="checkbox" class="form-checkbox rounded text-turquoise-400">
                                <span class="ml-2 text-gray-300">Technology</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-7" data-index="7">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Log in to your Dualis account
                </h1>
                <label class="block w-full">
                    <span class="text-gray-100">Email</span>
                    <input type="email" class="form-input mt-1 block w-full bg-transparent border-b border-gray-300 text-gray-300" placeholder="foo.bar@lehre.dhbw-stuttgart.de">
                </label>
                <label class="block w-full mt-10">
                    <span class="text-gray-100">Password</span>
                    <input type="password" class="form-input mt-1 block w-full bg-transparent border-b border-gray-300 text-gray-300" placeholder="Password">
                </label>
            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-8" data-index="8">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Choose your STONKS
                </h1>

            </div>
        </div>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/setup/progressbar.html" ?>
    </section>
    <section class="snap-box box-9 cursor-pointer" data-index="9">
        <div class="h-full flex flex-col justify-center items-center rounded-2xl">
            <div class="w-auto py-7 px-5 flex flex-col justify-center items-center">
                <h1 class="text-5xl text-gray-300 mb-8">
                    Setup finished!
                </h1>
                <span class="wave">&nbsp;</span>
            </div>
        </div>
    </section>
</div>
<script src="/views/setup/setup.js"></script>
</body>
</html>
