<!DOCTYPE html>
<html lang="en" id="darkSwitch" class="dark">
<head>
    <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body class="dark:bg-gray-300 fixed h-screen w-screen flex flex-col bg-gradient-to-br dark:from-gray-600 dark:via-gray-700 dark:to-gray-600">
    <div class="g-gradient-to-b dark:from-green-800 dark:to-gray-800 from-blue-100 to-green-200 w-full h-full">
        a
    </div>
</body>
<script src="/views/home/script.js"></script>
</html>
