<html>
    <head>
        <title>500 Internal Error</title>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <div class="container min-vh-80">
            <div class="text-center">
                <h3>Congratulations!</h3>
                <h4>You've encountered the Internal Error Unicorn!</h4>
                <img src="/resources/images/internal-error.png" alt="Internal Error Unicorn">
                <p class="small">(Watch out for the horn.)</p>
            </div>
            <div style="margin-top: 10%">
                <p>
                    A fatal error occured:
                    <?php
                    if (isset($isMessage) && $isMessage) {
                        echo $_SESSION['INTERNAL_ERROR'];
                    } else {
                        echo "No additional information was given.";
                    }
                    $_SESSION['INTERNAL_ERROR'] = null;
                    ?>
                    <br/>
                    Please contact the local site administrator with information on how to replicate this.<br/><br/>
                    <a href="/">Back to home</a>
                </p>
            </div>
        </div>
    </body>
</html>