version: '3.2'
services:
  web:
    container_name: web-server
    image: aswe-pda-frontend:1.0
    ports:
    - 8080:80
    networks:
      development:
    volumes:
    - type: bind
      source: "./src"
      target: "/var/www/html"
    - webserver:/data

volumes:
  webserver:

networks:
  development:
    driver: bridge
