openapi: 3.0.0
info:
  title: REST-API for T2S/S2T-Service
  description: Use this service to transfer text to speech and speech to text.
  version: 1.0

servers:
  - url: http://localhost:5555/rest/api/v1
    description: Port for docker version