openapi: 3.0.0
info:
  title: REST-API for Spotify-Service
  description: Use this Service to get information about a users Spotify profile.
  version: 1.0.0
  contact:
    name: API Support
    email: assadi.hakim@gmx.de
  license:
   name: MIT License
   url: https://github.com/lucastanger/aswe-pda/blob/main/LICENSE

servers:
  - url: http://localhost:5565/rest/api/v1
    description: Development server (using locally)
  - url: http://0.0.0.0:5565/rest/api/v1
    description: Production server (inside Docker)

paths:
  /auth:
    get:
      summary: Check if path is accessable.
      description: Returns a personalized user token to create requests.
      tags:
        - Spotify
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    description: An authorization code that can be exchanged for an access token.
                example:
                  message: To authorize with your Spotify profile use /rest/api/v1/auth.
                required:
                  - code

  /profile/info:
    get:
      summary: Check if path is accessable.
      description: Returns information about the Spotify profile informatio.
      tags:
        - Spotify profile info
      externalDocs:
        description: Spotify Web API Reference
        url: https://developer.spotify.com/documentation/web-api/reference/#category-user-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  country:
                    type: string
                    example: SE
                  display_name:
                    type: string
                    example: JM Wizzler
                  email:
                    type: string
                    example: email@example.com
                  external_urls:
                    type: object
                    properties:
                      spotify:
                        type: string
                        example: https://open.spotify.com/user/wizzler
                  followers:
                    type: object
                    properties:
                      href:
                        type: string
                        format: nullable
                      total:
                        type: integer
                        format: int32
                        example: 3829
                  href:
                    type: string
                    example: https://api.spotify.com/v1/users/wizzler
                  id:
                    type: string
                    example: wizzler
                  images:
                    type: array
                    items:
                      type: object
                      properties:
                        height:
                          type: string
                          format: nullable
                        url:
                          type: string
                          example: https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/t1.0-1/1970403_10152215092574354_1798272330_n.jpg
                        width:
                          type: string
                          format: nullable
                  product:
                    type: string
                    example: premium
                  type:
                    type: string
                    example: user
                  uri:
                    type: string
                    example: spotify:user:wizzler
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      status:
                        type: integer
                        format: int32
                        example: 403
                      message:
                        type: string
                        example: Forbidden
  /profile/playlist:
    get:
      summary: Check if path is accessable.
      description: Returns information about the associated playlists of the Spotify profile.
      tags:
        - Spotify playlist info
      externalDocs:
        description: Spotify Web API Reference
        url: https://developer.spotify.com/documentation/web-api/reference/#category-personalization
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    collaborative:
                      type: boolean
                    external_urls:
                      type: object
                      properties:
                        spotify:
                          type: string
                          example: http://open.spotify.com/user/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c
                    href:
                      type: string
                      example: https://api.spotify.com/v1/users/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c
                    id:
                      type: string
                      example: 53Y8wT46QIMz5H4WQ8O22c
                    images:
                      type: array
                      items:
                        example:
                    name:
                      type: string
                      example: Wizzlers Big Playlist
                    owner:
                      type: object
                      properties:
                        external_urls:
                          type: object
                          properties:
                            spotify:
                              type: string
                              example: http://open.spotify.com/user/wizzler
                        href:
                          type: string
                          example: https://api.spotify.com/v1/users/wizzler
                        id:
                          type: string
                          example: wizzler
                        type:
                          type: string
                          example: user
                        uri:
                          type: string
                          example: spotify:user:wizzler
                    public:
                      type: boolean
                    snapshot_id:
                      type: string
                      example: bNLWdmhh+HDsbHzhckXeDC0uyKyg4FjPI/KEsKjAE526usnz2LxwgyBoMShVL+z+
                    tracks:
                      type: object
                      properties:
                        href:
                          type: string
                          example: https://api.spotify.com/v1/users/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c/tracks
                        total:
                          type: integer
                          format: int32
                          example: 30
                    type:
                      type: string
                      example: playlist
                    uri:
                      type: string
                      example: spotify:user:wizzler:playlist:53Y8wT46QIMz5H4WQ8O22c
        '403':
            description: Forbidden
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: object
                      properties:
                        status:
                          type: integer
                          format: int32
                          example: 403
                        message:
                          type: string
                          example: Forbidden
