<!DOCTYPE html>
<html>
    <head>
        <title>404 Not Found</title>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
    </head>
    <body>
        <div class="container">
            <div class="container min-vh-80">
                <div class="text-center">
                    <h2>404 Not Found</h2>
                    <h4>Oh you, there's nothing here!</h4>
                    <img src="/resources/images/not-found.png" height="128px" alt="Not Found Pepe">
                </div>
            </div>
        </div>
    </body>
</html>