<!DOCTYPE html>
<html lang="en">
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
        <script type="module" src="/views/home/home.js"></script>
    </head>
    <body class="bg-gradient-to-br from-green-200 to-blue-200 h-screen w-screen p-28 justify-center 2xl:pl-64 2xl:pr-64">
        <p id="js-response"></p>
        <!-- Floating container -->
        <div class="rounded-3xl w-full h-5/6">
            <!-- header -->
            <div class="px-5 py-5 flex justify-between items-center bg-white dark:bg-gray-800 rounded-t-3xl border-b">
                <div class="font-semibold text-2xl dark:text-gray-100">
                    J.A.R.V.I.S - <span class="text-green-500">PDA</span>
                </div>

                <div class="h-12 w-12 p-2 bg-green-500 rounded-full text-white font-semibold flex items-center justify-center">
                    LS
                </div>
            </div>
            <!-- end header -->
            <!-- container -->
            <div class="flex content-start relative h-full rounded-b-3xl">
                <!-- start sidebar -->
                <div class="w-3/12 bg-white bg-opacity-95 rounded-bl-3xl flex-grow">
                    <div class="hover:bg-green-500 ml-3 mr-3 mt-1.5 rounded-md max-h-12 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" class="float-left">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                        </svg>
                        <span class="">&nbsp;Chat</span>
                    </div>
                    <div class="hover:bg-green-500 ml-3 mr-3 mt-1.5 rounded-md max-h-12 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" class="float-left">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
                        </svg>
                        <span class="">&nbsp;History</span>
                    </div>
                    <div class="hover:bg-green-500 ml-3 mr-3 mt-1.5 rounded-md max-h-12 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" class="float-left">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                        <span class="">&nbsp;Profile</span>
                    </div>
                    <div class="hover:bg-green-500 ml-3 mr-3 mt-1.5 rounded-md max-h-12 p-2">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" class="float-left">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                        </svg>
                        <span class="">&nbsp;Design</span>
                    </div>

                </div>
                <!-- end sidebar -->
                <!-- chat container -->
                <div class="w-full flex flex-col relative ">
                    <div class="bg-white bg-opacity-40 p-10 justify-center h-full rounded-br-3xl">
                        <div class="">

                            <!-- SINGLE MESSAGE -->
                            <div class="clearfix">
                                <div class="bg-gray-300 w-3/6 mx-4 my-2 p-2 rounded-lg">Hello! My name is J.A.R.V.I.S. How may I help you today?</div>
                            </div>

                            <!-- SINGLE MESSAGE 3 -->
                            <div class="clearfix">
                                <div class="bg-green-300 float-right w-auto mx-4 my-2 p-2 rounded-lg right-0">How is the weather today?</div>
                            </div>

                        </div>

                    </div>
                    <!-- Input -->
                    <div class="justify-end flex-col w-full bg-gray-100 rounded-br-3xl absolute bottom-0 right-0">
                        <div class="grid grid-cols-12">
                            <div class="col-span-11">
                                <input class="bg-gray-100 py-5 px-3 rounded-br-xl w-full" type="text" placeholder="Write a message" />
                            </div>
                            <div class="col-span-1 m-auto">
                                <a href="#">
                                    <span>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" width="35" height="35" stroke="currentColor" class="text-gray-500">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                                        </svg>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- end input -->
                </div>

                <!-- end chat container -->
            </div>
            <!-- end container -->
        </div>
        <!-- end floating container -->

    </body>
</html>

<!---->