<!DOCTYPE html>
<html lang="en">
    <head>
        <?php include "{$_SERVER['DOCUMENT_ROOT']}/views/shared/shared.phtml" ?>
        <script type="module" src="/views/home/home.js"></script>
    </head>
    <body class="bg-gradient-to-br from-green-200 to-red-300 h-screen">
        <p id="js-response"></p>
        <div class="content-center">
            <h1>test</h1>
        </div>
    </body>
</html>