name: Black Code 

on: push

jobs:
  format-code:
    name: Format code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Black Code Formatter
        uses: jpetrucciani/black-check@20.8b1
        with:
          path: src/backend/services/*
